- name: Copy custom cluster files to container
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/tmp/{{ item.dest }}"
    mode: 'u=rw,g=r,o=r'
  with_items:
    - { src: "fixtures/clusters.d/my_cluster.yml", dest: "my_cluster.yml" }
    - { src: "fixtures/clusters.d/another_cluster.yml", dest: "another_cluster.yml" }
    - { src: "fixtures/apps/dashboard.env", dest: "dashboard.env" }
    - { src: "fixtures/apps/files.env", dest: "files.env" }
    - { src: "fixtures/apps/bc_desktop/", dest: "bc_desktop/" }
    - { src: "fixtures/config/auth_openidc.conf", dest: "auth_openidc.conf" }
    - { src: "fixtures/ondemand.d/ondemand_custom.yml", dest: "ondemand.yml" }

- name: Verify config files
  ansible.builtin.command: "diff /tmp/{{ item.left }} {{ item.right }}"
  with_items:
    - { left: "dashboard.env", right: "{{ ood_base_conf_dir }}/apps/dashboard/env" }
    - { left: "files.env", right: "{{ ood_base_conf_dir }}/apps/files/env" }
    - { left: "my_cluster.yml", right: "{{ ood_base_conf_dir }}/clusters.d/my_cluster.yml" }
    - { left: "another_cluster.yml", right: "{{ ood_base_conf_dir }}/clusters.d/another_cluster.yml" }
    - { left: "bc_desktop/my_cluster.yml", right: "{{ ood_base_conf_dir }}/apps/bc_desktop/my_cluster.yml" }
    - { left: "bc_desktop/submit/submit.yml.erb", right: "{{ ood_base_conf_dir }}/apps/bc_desktop/submit/submit.yml.erb" }
    - { left: "auth_openidc.conf", right: "{{ apache_conf_dir }}/auth_openidc.conf" }
    - { left: "ondemand.yml", right: "{{ ood_base_conf_dir }}/ondemand.d/ondemand.yml" }
  changed_when: false

- name: Verify sys/jupyter was installed correctly
  ansible.builtin.git:
    repo: 'https://github.com/OSC/bc_example_jupyter.git'
    dest: '/var/www/ood/apps/sys/jupyter'
    clone: no
    update: no
    version: master

- name: Verify dev/customdir app was installed correctly
  ansible.builtin.git:
    repo: 'https://github.com/OSC/bc_example_jupyter.git'
    dest: '/var/www/ood/apps/dev/customdir'
    clone: no
    update: no
    version: v1.0.1