- name: Verify ondemand.d/ondemand.yml file is empty
  ansible.builtin.shell: |
    if [[ -n $(grep '[^[:space:]]' /etc/ood/config/ondemand.d/ondemand.yml) ]]; then 
      false
    fi
  args:
    executable: /bin/bash
  changed_when: false
