- name: make a tmp staging directory
  file:
    path: "{{ ood_source_dir }}"
    state: directory

- name: get the source code
  git:
    repo: "{{ ood_source_repo }}"
    dest: "{{ ood_source_dir }}"
    version: "{{ ood_source_version }}"
    force: yes

- name: clean up to ensure proper build
  shell: rake clean
  args:
    chdir: "{{ ood_source_dir }}"

- name: build the project (this will take some time)
  shell: "rake build -mj$(nproc) > build.out 2>&1"
  args:
    chdir: "{{ ood_source_dir }}"
