- name: Create clusters.d directory
  file:
    path: "{{ ood_base_conf_dir }}/clusters.d"
    mode: 'u=rwx,g=rx,o=rx'
    state: directory

- name: Add cluster configuration files
  copy:
    content: "{{ item.value | to_nice_yaml }}"
    dest: "{{ ood_base_conf_dir }}/clusters.d/{{ item.key }}.yml"
    mode: 'u=rw,g=r,o=r'
  loop: "{{ clusters | default({}) | dict2items }}"
