# This file holds defaults for installing Open OnDemand apps. There are no
# default configuration for apps, because they're site specific.
# This file is meant to provide an example for your own variable files.

## Manage cluster example, default undef
# cluster:
#   my_cluster: |
#     ---
#     v2:
#       metadata:
#         title: my_cluster
#       login:
#         host: my_host
#       job:
#         adapter: slurm
#         bin: /usr/local
#       batch_connect:
#
## Apps install example, default undef
# ood_install_apps:
#   jupyter:
#     repo: https://github.com/OSC/bc_example_jupyter.git
#     dest: {{ ood_sys_app_dir }}  # default creates
#     version: master        # default
#     umask: '022' # default,File=rw-r-r,Dir=rwx-rx-rx
#   customdir: # will create /var/www/ood/apps/my/dir/customdir
#     repo: https://github.com/OSC/bc_example_jupyter.git
#     dest: /var/www/ood/apps/my/dir
#     version: v1.0.1
#     umask: '002'
#
## Apps config example, default undef
# ood_apps:
#   bc_desktop:
#     title: "remote desktop"
#     cluster: my_cluster
#     attributes:
#       desktop: xfce
#     submit: |
#       ---
#       script:
#         native:
#           - "<%= bc_num_slots.blank? ? 1 : bc_num_slots.to_i %>"
#           - "1"
#   files:
#     env:
#       ood_shell: /bin/bash
#   dashboard:
#     env:
#       motd_format: markdown
#     initializers: 'files/ood/dashboard/'
#
