# This file holds all the defaults for the /etc/ood/ondemand.d/ondemand.yml. This role
# supplies no defaults and so this file is only meant to be an example for your own
# var files.
# 
# See https://osc.github.io/ood-documentation/latest/reference/files/ondemand-d-ymls.html
# for more details on this file and it's configurations.


# pinned_apps:
#   - "sys/*"
#   - field_of_science: 'biology'
#   - type: sys
#     category: 'system'
#   - type: sys
#     category: 'minimal'
#     subcategory: 'class_instruction'
#     field_of_science: 'biology'

# pinned_apps_menu_length: 10
# pinned_apps_group_by: category

# dashboard_layout:
#   rows:
#     - columns:
#       - width: 8
#         widgets:
#           - pinned_apps
#           - motd
#       - width: 4
#         widgets:
#           - xdmod_widget_job_efficiency
#           - xdmod_widget_jobs

# support_ticket:
#   attachments:
#     max_items: 4
#     max_size: 2097152
#   description: |
#     My optional description Text for the support ticket feture
#   email:
#     from: "config@example.com"
#     to: "support@example.com"
#     delivery_method: "smtp"
#     delivery_settings:
#       address: 'smtp.gmail.com'
#       port: 587
#       domain: 'example.com'
#       user_name: '<username>'
#       password: '<password>'
#       authentication: 'plain'
#       enable_starttls_auto: true
#       open_timeout: 15
#       read_timeout: 15

# help_menu:
#   - group: "Documentation"
#   - title: "Jupyter Docs"
#     icon: "fas://book"
#     url: "https://mydomain.com/path/jupyter"
#   - title: "Support Docs"
#     icon: "fas://book"
#     url: "https://mydomain.com/path/support/docs"
#   - group: "Custom Pages"
#   - page: "rstudio_guide"
#     title: "RStudio Guide"
#     icon: "fas://window-restore"
#   - group: "Profiles"
#   - profile: "team1"
#     title: "Team 1"
#     icon: "fas://user"
