# This file holds all the defaults for the /etc/ood/ondemand.d/ondemand.yml. This role
# supplies no defaults and so this file is only meant to be an example for your own
# var files.
# 
# See https://osc.github.io/ood-documentation/latest/reference/files/ondemand-d-ymls.html
# for more details on this file and it's configurations.


# pinned_apps:
#   - "sys/*"
#   - field_of_science: 'biology'
#   - type: sys
#     category: 'system'
#   - type: sys
#     category: 'minimal'
#     subcategory: 'class_instruction'
#     field_of_science: 'biology'

# pinned_apps_menu_length: 10
# pinned_apps_group_by: category

# dashboard_layout:
#   rows:
#     - columns:
#       - width: 8
#         widgets:
#           - pinned_apps
#           - motd
#       - width: 4
#         widgets:
#           - xdmod_widget_job_efficiency
#           - xdmod_widget_jobs
