---
- name: Converge
  hosts: default
  roles:
    - role: ood-ansible
  vars:
    rpm_repo_url: "https://yum.osc.edu/ondemand/latest/ondemand-release-web-latest-1-7.noarch.rpm"
    apt_repo_url: "https://apt.osc.edu/ondemand/latest/ondemand-release-web-latest_2_all.deb"
    ondemand_package: "ondemand{% if ansible_os_family == 'RedHat' %}-{% else %}={% endif %}2.0.29"
    nodejs_version: 14