---
- name: Converge
  hosts: default
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: vars/converge.yml
    - name: run role
      ansible.builtin.include_role:
        name: ood-ansible
    