- name: Prepare
  hosts: all
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install missing packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - ca-certificates
      - systemd
      - git

- name: Install previous version
  hosts: all
  roles:
    - role: ood-ansible
  vars_files:
    - vars/prepare.yml
