- name: Prepare
  hosts: all
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install missing packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - ca-certificates
      - systemd
      - git

    - name: Install extra packages (EL10)
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - gpg2
      when:  ansible_os_family == "RedHat" and ansible_distribution_major_version == '10'

- name: Install previous version
  hosts: all

  pre_tasks:
    - name: Set dependency versions on el8
      set_fact:
        ruby_version: 3.3
        nodejs_version: 20
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= '8'

    - name: Use default versions on el9
      set_fact:
        additional_rpm_installs:
          - lua-posix
          - "@ruby:{{ ruby_version }}"
          - "@nodejs:{{ nodejs_version }}"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '9'

  roles:
    - role: ood-ansible
  vars_files:
    - vars/prepare.yml
