- name: Prepare
  hosts: all
  
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install missing packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - ca-certificates
      - systemd
      - git

    - name: Install extra packages (EL10)
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - gnupg2
      when:  ansible_os_family == "RedHat" and ansible_distribution_major_version == '10'

    - name: Install extra packages (Debian)
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - apt-key
      when:  ansible_os_family == "Debian"

- name: Install previous version
  hosts: all
  roles:
    - role: ood-ansible
  vars_files:
    - vars/prepare.yml
