ondemand_package: "ondemand{% if ansible_os_family == 'RedHat' %}-{% else %}={% endif %}3.1.10"
disable_htcacheclean: true
apt_repo_url: "https://apt.osc.edu/ondemand/3.1/ondemand-release-web_3.1.2_all.deb"
rpm_repo_url: "https://yum.osc.edu/ondemand/3.1/ondemand-release-web-3.1-1.noarch.rpm"
