clusters:
  another_cluster:
    v2:
      metadata:
        title: Another Cluster
  my_cluster:
    v2:
      metadata:
        title: my_cluster
      login:
        host: my_host
      job:
        adapter: slurm
        bin: /usr/local
      batch_connect:

ood_install_apps:
  jupyter:
    repo: https://github.com/OSC/bc_example_jupyter.git
  customdir:
    repo: https://github.com/OSC/bc_example_jupyter.git
    dest: "/var/www/ood/apps/dev/"
    version: v1.0.1
ood_apps:
  bc_desktop:
    title: "remote desktop"
    cluster: my_cluster
    attributes:
      desktop: xfce
    submit: |
      script:
        native:
          - '<%= bc_num_slots.blank? ? 1 : bc_num_slots.to_i %>'
          - '1'
  files:
    env:
      ood_shell: /bin/bash
  dashboard:
    env:
      motd_format: markdown
      ood_dataroot: "/mnt/newfs/$USER"

apache_service_enabled: true

# ood_portal.yml configs
host_regex: 'forge-(l|c)\d+'
user_map_cmd: '/opt/ood/ood_auth_map/bin/ood_auth_map.regex --regex=''''^([A-Za-z0-9\-_\.]+)@osc.edu$'''''
rnode_uri: '/custom-rnode-path'
node_uri: '/custom-node-path'
oidc_uri: '/custom-oidc-path'

ood_auth_openidc:
  OIDCSessionMaxDuration: 28888
  OIDCClientID: myid
  OIDCProviderMetadataURL: https://localhost/
  OIDCCryptoPassphrase: mycryptopass


# nginx_stage.yml configs
nginx_min_uid: 500
user_regex: '^[A-Za-z0-9\-_\.]+@osu.edu$'
