# nginx_stage.yml custom configurations
nginx_min_uid: 500
user_regex: '^[A-Za-z0-9\-_\.]+@osu.edu$'
pun_log_format: '$status|"$http_referer"|"$http_user_agent"|"$http_x_forwarded_for|$body_bytes_sent|$remote_addr|$remote_user|$time_local|"$request"'

passenger_pool_idle_time: 400
passenger_options:
  passenger_stat_throttle_rate: 60

pun_custom_env:
  MY_ENV_VAR: 'is so cool'
