pinned_apps:
  - "usr/*"
  - field_of_science: 'biology'
  - type: dev
    category: 'system'
  - type: sys
    category: 'minimal'
    subcategory: 'class_instruction'
    field_of_science: 'biology'

pinned_apps_menu_length: 10
pinned_apps_group_by: category

dashboard_layout:
  rows:
    - columns:
      - width: 8
        widgets:
          - pinned_apps
          - motd
      - width: 4
        widgets:
          - xdmod_widget_job_efficiency
          - xdmod_widget_jobs


support_ticket:
  attachments:
    max_items: 4
    max_size: 6291456
  description: 'My optional description Text for the support ticket feture '
  email:
    from: config@example.com
    to: support@example.com
