# custom ood_portal.yml configurations
host_regex: 'forge-(l|c)\d+'
# nobody's should be using both user_* configs here, but this is a test after all
user_map_cmd: '/opt/site/regex-mapper --regex=''''^([A-Za-z0-9\-_\.]+)@osc.edu$'''''
user_map_match: '^([^@]+)@.*$'
rnode_uri: '/custom-rnode-path'
node_uri: '/custom-node-path'
oidc_uri: '/custom-oidc-path'
secure_node_uri: '/custom-secure-node'
secure_rnode_uri: '/custom-secure-rnode'
ssl_proxy:
  - 'SSLProxyCheckPeerCN Off'
  - 'SSLProxyCheckPeerName Off'
httpd_error_log: 'custom_defined_error.log'
httpd_access_log: 'custom_defined_access.log'
httpd_logformat: '"%O %h \"%{Referer}i\" \"%r\" %v \"%{User-Agent}i\" %{SSL_PROTOCOL}e %T %>s"'
security_csp_frame_ancestors: http://my.proxy.server.edu
security_strict_transport: true
pun_pre_hook_exports: 'OIDC_ACCESS_TOKEN,OIDC_CLAIM_EMAIL'
pun_pre_hook_root_cmd: '/opt/site/site_pre_hook'

custom_vhost_directives:
  - '<Location "/test">'
  - '  SetEnv SPECIAL_PATH /foo/bin'
  - '</Location>'

custom_location_directives:
  - 'SetEnv SPECIAL_PATH /foo/bin'

server_aliases:
  - other-site.notrealdoman.edu

ood_auth_openidc:
  OIDCSessionMaxDuration: 28888
  OIDCClientID: myid
  OIDCProviderMetadataURL: https://localhost/
  OIDCCryptoPassphrase: mycryptopass

strip_proxy_cookies: ["mod_auth_openidc_session"]
strip_proxy_headers: ["Authorization", "OIDC_access_token"]

register_method: Alias
register_method_options:
  - 'WSGIDaemonProcess register user=www-data group=www-data threads=5 home=/var/www/flask-apps/register'