---
- name: Converge
  hosts: default
  roles:
    - role: ood-ansible

- name: Custom
  hosts: custom
  roles:
    - role: ood-ansible
  vars_files:
    - vars/apps.yml
    - vars/nginx.yml
    - vars/portal.yml

- name: Pam auth
  hosts: default
  roles:
    - role: ood-ansible
  vars_files:
    - vars/pam_auth.yml
