---
- name: Converge
  hosts: instance
  roles:
    - role: ood-ansible
      ood_portal_generator: false
      rnode_uri: "/myrnode"

- name: Custom
  hosts: custom
  roles:
    - role: ood-ansible
      clusters:
        another_cluster:
          v2:
            metadata:
              title: Another Cluster
        my_cluster:
          v2:
            metadata:
              title: my_cluster
            login:
              host: my_host
            job:
              adapter: slurm
              bin: /usr/local
            batch_connect:
      nginx_min_uid: 500
      apache_service_enabled: true
      ood_install_apps:
        jupyter:
          repo: https://github.com/OSC/bc_example_jupyter.git
        customdir:
          repo: https://github.com/OSC/bc_example_jupyter.git
          dest: "/var/www/ood/apps/dev/"
          version: v1.0.1
      ood_apps:
        bc_desktop:
          title: "remote desktop"
          cluster: my_cluster
          attributes:
            desktop: xfce
          submit: |
            script:
              native:
                - '<%= bc_num_slots.blank? ? 1 : bc_num_slots.to_i %>'
                - '1'
        files:
          env:
            ood_shell: /bin/bash
        dashboard:
          env:
            motd_format: markdown
            ood_dataroot: "/mnt/newfs/$USER"
      oidc_uri: /oidc
      ood_auth_openidc:
        OIDCSessionMaxDuration: 28888
        OIDCClientID: myid
        OIDCProviderMetadataURL: https://localhost/
        OIDCCryptoPassphrase: mycryptopass

- hosts: all
  tasks:
    - name: create ood user
      user:
        name: ood
    - name: create debug user apache auth user ood:ood
      copy:
        content: 'ood:$apr1$EOza4zZK$fuKLibf.WGN2E5MuovgQs.'
        dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
