---
dependency:
  name: galaxy

driver:
  name: ${CONTAINER_RT:-docker}

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: default
    image: ${IMAGE:-"centos:7"}
    command: /sbin/init
    tmpfs:
      "/run": "rw"
      "/tmp": "rw"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: custom
    image: ${IMAGE:-"centos:7"}
    command: /sbin/init
    tmpfs:
      "/run": "rw"
      "/tmp": "rw"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: oidc
    image: ${IMAGE:-"centos:7"}
    command: /sbin/init
    tmpfs:
      "/run": "rw"
      "/tmp": "rw"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
