- name: Prepare
  hosts: all
  
  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install extra packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
      - ca-certificates
      - systemd
      - git
