- name: Prepare
  hosts: all
  
  tasks:
    - apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - package:
        name: "{{ item }}"
        state: latest
      loop:
      - ca-certificates
      - systemd
      - git
